### ISSUE TITLE
Text object doesn't select the same part as the gX commands

### ISSUE THREAD

**Issue by hoschi** [machakann/vim-swap#10]
Teststring:
`const other = console.log(myFun('thing', 'otherthing'), ['bar'].map((el, i) => el+i), 'next')`

Place cursor on the first `[`.

* `gs`: corectly selects `['bar'].map((el, i) => el+i)` and starts interactive mode
* `vi,`: selects `'bar'` instead of the above, I expected the same selection as with `gs`

**Comment by machakann** [comment]
Sorry for my late response, I missed this issue.

I reproduced the situation, but it seems this is expected behavior. As you think, `gs` and `i,` should work similarly but this is the only case they behave differently for convenience. For example, `gs` should work with multiple items,

```
func(foo, bar, baz)
```

but shouldn't work with only an item,

```
func(qux)
```

because there is no room to swap. However, I think it is convenient and consistent the `qux` is also selected with the textobject `i,` similar to `foo`, `bar`, and `baz`. So you may find this weird but this is intentionally implemented. It might not be so elegant but please move the cursor one character left of `[` practically.

Related discussion is in #8

**Comment by hoschi** [comment]
Thanks for the explanation, didn't see that moving the cursor to the white space would fix it.
