### ISSUE TITLE
Feature request: support `:sort`

### ISSUE THREAD

**Issue by alexanderbird** [machakann/vim-swap#9]
Hi @machakann, if you're working on this actively, there is a feature I would love to have:

```
doSomething(
  'a',
  'c',
  'd',
  'b'
)
```
I want to sort the arguments alphabetically -- usually by visually selecting the lines, then using the built-in `:sort` command.

This doesn't handle the trailing comma properly, and results in 

```
doSomething(
  'a',
  'b'
  'c',
  'd',
)
```

Which requires manually fixing the comma.

--------------
In addition to vanilla sorting, I also tend to use `:sort u` to remove duplicates and `:sort!` to sort in reverse order

-------------
If you don't have time/interest in working on that, would you be open to a pull request from me? Not sure when I'll have time, but I might sooner or later

**Comment by alexanderbird** [comment]
I'm imagining a custom command to sort in an argument-list-aware sort of way

```
foo(1,3,2)
```
Visually select 1 through 2 `0f1v2` then execute something like `:SSort` to produce

```
foo(1,2,3)
```

**Comment by machakann** [comment]
Honestly, I also want this. I will try to work on it this weekend.

**Comment by machakann** [comment]
Hi, it takes so long but I finally merged the "sort" feature to the master branch.

The new function can be employed in swap mode as a key sequence `s` or `S`, for example press `gss<Esc>` to sort items in ascending order.

Or, you can swap items in the current buffer by a function `swap#region({start}, {end}, {type}, {input})`. vim-swap does not provide any commands in default now (because command works linewise always in principle however vim-swap can do more!), but `SSort` can be easily defined, for example:

```vim
command! -range SSort call swap#region("'<", "'>", visualmode(),
\ [['sort', {x, y -> x.str is# y.str ? 0 : x.str < y.str ? -1 : 1}]])
```

Thank you for your request! After I tested this, then immediately I started to love the feature.

**Comment by alexanderbird** [comment]
🎉 Woo hoo!! Works wonderfully, thanks so much! Nice work! 

👍 👍 

![celebrating](https://media.giphy.com/media/Is1O1TWV0LEJi/giphy.gif)
